# Generated by Django 4.2.11 on 2024-07-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0002_websites'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='sitemap',
            field=models.TextField(default=''),
        ),
    ]
