# Generated by Django 5.0.7 on 2024-07-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0004_alter_websites_delivry_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='delivry_price',
            field=models.CharField(max_length=200),
        ),
    ]
